# Generated by Django 5.1.7 on 2025-05-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_cart_cartitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="WomenCologne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=60.0, max_digits=6),
                ),
                (
                    "original_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("image", models.ImageField(upload_to="colognes/")),
                ("additional_images", models.JSONField(blank=True, default=list)),
                (
                    "scent_type",
                    models.CharField(
                        choices=[
                            ("floral", "Floral"),
                            ("fresh", "Fresh"),
                            ("romantic", "Romantic"),
                            ("night", "Night"),
                        ],
                        max_length=20,
                    ),
                ),
                ("top_notes", models.JSONField(blank=True, default=list)),
                ("rating", models.FloatField(default=4.7)),
            ],
        ),
    ]
