# Generated by Django 5.1.7 on 2025-05-02 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_womencologne"),
    ]

    operations = [
        migrations.CreateModel(
            name="WomenCartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="women_items",
                        to="accounts.cart",
                    ),
                ),
                (
                    "cologne",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.womencologne",
                    ),
                ),
            ],
        ),
    ]
